[package]
name = "equip-penguin"
version = "0.0.0"
authors = [ "Angry Penguins",]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.25.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.25.0"
