[package]
name = "customize_nft-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.customize_nft]
path = ".."

[dependencies.elrond-wasm]
version = "0.29.3"

[dependencies.elrond-wasm-debug]
version = "0.29.3"
