name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup nightly
      run: rustup toolchain install nightly && rustup default nightly && rustup target add wasm32-unknown-unknown    
    - name: Install requirements for code coverage
      run: cargo install grcov  
    - name: Test + Measure code coverage
      run: |
        chmod +x ./coverage.sh
        ./coverage.sh lcov
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: "./target/debug/coverage.lcov"
        verbose: true # optional (default = false)
    - name: Build
      run: cargo build --verbose
